# Generated by Django 3.2.8 on 2021-10-14 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Código de Endereço Postal')),
                ('endereco', models.CharField(blank=True, default=None, help_text='Nome da Rua/Endereço', max_length=300, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, default=None, max_length=160, null=True, verbose_name='Complemento')),
                ('uf', models.CharField(blank=True, default=None, help_text='Unidade Federativa', max_length=2, null=True, verbose_name='UF')),
                ('estado', models.CharField(blank=True, default=None, help_text='Estado', max_length=150, null=True, verbose_name='Estado')),
                ('bairro', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Cidade')),
                ('pais', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='País')),
                ('observacao', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Observação')),
                ('ibge', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='IBGE')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do Pagamento Realizado')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default=None, max_length=191, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=191, verbose_name='Nome')),
                ('cpf', models.CharField(default=None, max_length=14, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, default=None, null=True)),
                ('sexo', models.PositiveIntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Feminino'), (3, 'Outro'), (4, 'Indefinido')], default=4, help_text='Sexo', null=True, verbose_name='Sexo')),
                ('tel_cel', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Telefone Celular')),
                ('email', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Telefone Fixo')),
                ('gerente', models.BooleanField(default=False, help_text='Se Pessoa é Gerente', verbose_name='Gerente')),
                ('cliente', models.BooleanField(default=False, help_text='Se Pessoa é Cliente', verbose_name='Cliente')),
                ('func', models.BooleanField(default=False, help_text='Se Pessoa é Funcionario', verbose_name='Funcionário')),
                ('funcionario_ativo', models.BooleanField(blank=True, default=True, null=True, verbose_name='Funcionario Ativo')),
                ('cliente_ativo', models.BooleanField(blank=True, default=True, null=True, verbose_name='Cliente Ativo')),
                ('gerente_ativo', models.BooleanField(blank=True, default=True, null=True, verbose_name='Gerente Ativo')),
                ('enderecos', models.ManyToManyField(to='core.Endereco', verbose_name='Endereços do Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=None, null=True)),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, 'Pendente'), (2, 'Em Andamento'), (3, 'Aguardando Pagamento'), (4, 'Concluido'), (5, 'Cancelado')], default=5, help_text='Status do Agendamento', null=True, verbose_name='Status')),
                ('cliente', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_agendamentos', to='core.pessoa')),
                ('funcionario', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionario_agendamentos', to='core.pessoa')),
                ('pagamentos', models.ManyToManyField(blank=True, default=None, null=True, related_name='agendamento', to='core.Pagamentos')),
                ('servicos', models.ManyToManyField(blank=True, default=None, null=True, related_name='agendamento', to='core.Servicos')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='pessoa',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='core.pessoa'),
        ),
    ]
