# Generated by Django 3.2.8 on 2021-10-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211013_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cliente',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cliente',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='cliente_agendamentos', to='core.Pessoa'),
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='funcionario',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='funcionario_agendamentos', to='core.Pessoa'),
        ),
    ]
