# Generated by Django 3.2.8 on 2021-10-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211020_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ManyToManyField(blank=True, default=None, related_name='cliente_agendamentos', to='core.Pessoa'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='funcionario',
            field=models.ManyToManyField(blank=True, default=None, related_name='funcionario_agendamentos', to='core.Pessoa'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='pagamentos',
            field=models.ManyToManyField(blank=True, default=None, related_name='agendamento', to='core.Pagamentos'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servicos',
            field=models.ManyToManyField(blank=True, default=None, related_name='agendamento', to='core.Servicos'),
        ),
    ]
